### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by jcgay** [jcgay/protector#8]
```
./protector -dry-run -repos softwarevidal/a****r -token $GITHUB_TOKEN                                                                                                     

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12376d2]

goroutine 40 [running]:
main.(*githubProtection).lock(0xc420086230, 0xc420120000, 0xc42020db40, 0x102d3ea, 0x0, 0xc4202e1720, 0x0)
	/Users/jcgay/dev/golang/src/github.com/jcgay/protector/protection.go:90 +0x32
main.(*githubProtection).protect.func1(0xc42020db40, 0xc420120000, 0xc420122050, 0x1, 0x1)
	/Users/jcgay/dev/golang/src/github.com/jcgay/protector/protection.go:50 +0x3d
main.(*githubProtection).process(0xc420086230, 0xc420120000, 0xc420053f78)
	/Users/jcgay/dev/golang/src/github.com/jcgay/protector/protection.go:39 +0x170
main.(*githubProtection).protect(0xc420086230, 0xc420120000)
	/Users/jcgay/dev/golang/src/github.com/jcgay/protector/protection.go:49 +0x55
main.main.func2(0xc4200185c0, 0xc420086230, 0xc420120000)
	/Users/jcgay/dev/golang/src/github.com/jcgay/protector/protector.go:129 +0x92
created by main.main
	/Users/jcgay/dev/golang/src/github.com/jcgay/protector/protector.go:123 +0x6d7
```

**Comment by jcgay** [comment]
https://github.com/google/go-github/pull/626
https://github.com/google/go-github/issues/625

**Comment by jcgay** [comment]
It seems that the Protected state is not returned anymore when listing branches...

    https://api.github.com/repos/softwarevidal/a*****r/branches

Will have to call `GetBranch` for each branch to read protection status.

    https://api.github.com/repos/softwarevidal/a*****r/branches/master
